## Forestry

### Harvest Flow

The following chart shows **harvest area**:

```{r harvest_area, results = 'asis', dpi=300}
data <- params$reportList$harvest[, sum(area), by = c("scenario", "timeperiod")]
data$scenario <- reorder(data$scenario, data$V1, function(x) - max(x))
data[, timeperiod := as.integer(timeperiod)]

ggplot(data, aes (x = timeperiod, y = V1, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Area Harvested (ha)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

The following chart shows **harvest volume**:

```{r harvest_volume, results = 'asis', dpi=300}
data <- params$reportList$harvest[, sum(volume), by = c("scenario", "timeperiod")]
data$scenario <- reorder(data$scenario, data$V1, function(x) - max(x))
data[, timeperiod := as.integer(timeperiod)]
ggplot (data, aes (x = timeperiod, y = V1, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Volume Harvested (m3)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

### Transition Harvest

```{r trnasition_harvest, results = 'asis', dpi=300}
data <- params$reportList$harvest[, sum(transition_area), by = c("scenario", "timeperiod")]
data$scenario <- reorder(data$scenario, data$V1, function(x) - max(x))
data[, timeperiod := as.integer(timeperiod)]
ggplot(data, aes (x = timeperiod, y = V1, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Managed Area Harvested (ha)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

```{r managed_volume, results = 'asis', dpi=300}
data <- params$reportList$harvest[, sum(transition_volume), by = c("scenario", "timeperiod")]
data$scenario <- reorder(data$scenario, data$V1, function(x) - max(x))
data[, timeperiod := as.integer(timeperiod)]
ggplot(data, aes (x = timeperiod, y = V1, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Managed Volume Harvested (m3)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

### Harvest Age

```{r harvest_age, results = 'asis', dpi=300}
data <- params$reportList$harvest
data <- data[, lapply(.SD, FUN = weighted.mean, x = age), by = c("timeperiod", "scenario"), .SDcols = 'age']
data[, timeperiod := as.integer(timeperiod)]

ggplot (data, aes (x = timeperiod, y = age, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Average Harvest Age (yrs)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

### Available THLB

```{r thlb, results = 'asis', dpi=300}
data <- params$reportList$harvest[, sum(avail_thlb), by = c("scenario", "timeperiod")]
data$scenario <- reorder(data$scenario, data$V1, function(x) - max(x))
data[, timeperiod := as.integer(timeperiod)]
ggplot (data, aes (x = timeperiod, y = V1, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Available THLB (ha)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

### Growingstock

```{r growingstock, results = 'asis', dpi=300}
data <- params$reportList$growingstock
data$scenario <- reorder(data$scenario, data$growingstock, function(x) - max(x))
ggplot(data, aes (x = timeperiod, y = growingstock, fill = scenario)) +
  geom_area(position = "identity", aes(alpha = scenario)) +
  xlab ("Future year") +
  ylab ("Growing Stock (m3)") +
  scale_x_continuous(breaks = seq(0, max(data$timeperiod), by = 10)) +
  scale_alpha_discrete(range = c(0.4, 0.8)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
  )
```

